---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  test_repo_uri: "https://github.com/ehaselwanter/tests-kitchen-example.git"

platforms:
  - name: nocm_ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-12.04
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
  - name: nocm_ubuntu-13.10
    driver_plugin: vagrant
    driver_config:
      box: nocm_ubuntu-13.10
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-1310-x64-virtualbox-nocm.box

suites:
- name: default
  manifest: site.pp